# action.yml
name: "kiwitcms/gitops"
description: "development & testing swiss-army tool"
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  anonymous-analytics:
    description: >
      Anonymous analytics via Plausible.io.
    default: "true"
  debug:
    description: >
      Log debugging information
    default: "false"
  reply-to-comments:
    description: >
      Post command output as replies to comments triggering this action
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "green"
  icon: "user-plus"
