#!/usr/bin/env python

"""
Entrypoint for the kiwitcms/gitops application!
This is meant to be executed as a command line application triggered
via a pull request comment!
"""
#
# Copyright (c) 2024 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under the AGPL-3.0: https://www.gnu.org/licenses/agpl-3.0.html
#
import os
import sys

root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(root_path)

import click
import sentry_sdk

from app.analytics import analyze
from app import event
from app.utils import strtobool
from app.version import __version__


@analyze("main")
def main():
    click.echo("Hello from main() function!")

    trigger_event = event.load()

    if strtobool(os.environ.get("INPUT_DEBUG", "false")):
        import pprint

        click.echo("==== ENVIRONMENT ====")
        click.echo(pprint.pformat(dict(os.environ)))

        click.echo("===== TRIGGER EVENT ====")
        click.echo(pprint.pformat(trigger_event.payload))
        click.echo("===================")

    # /use/bin/gh repo clone trigger_event["repository"]["clone_url"] .
    # trigger_event.payload["issue"]["number"]
    # /usr/bin/gh pr checkout https://github.com/kiwitcms/gitops/pull/16

    # TODO: parse github.event JSON and call cli() with a list of arguments
    # based on what we should do or the contents of a PR comment
    cli(sys.argv[1:])


@click.group(invoke_without_command=True)
def cli():
    pass


@analyze("help")
@cli.command()
def help():
    click.echo(cli.get_help(click.get_current_context()))


if __name__ == "__main__":
    sentry_sdk.init(
        dsn="https://e9a370eba7bd41fe8faead29552f12d7@o126041.ingest.sentry.io/277775",
        enable_tracing=False,
        release=__version__,
    )
    main()
