name: DEBUG kiwitcms/gitops

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  on-pr-comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@kiwitcms')
    # checkov:skip:CKV2_GHA_1:Action needs to write back comments & PRs
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.rest.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name

      - name: Execute kiwitcms/gitops during development
        uses: ./ # Uses an action in the root directory
        with:
          debug: true
