name: kiwitcms/gitops

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  on-pr-comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@kiwitcms')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute kiwitcms/gitops
        uses: ./ # Uses an action in the root directory
