name: kiwitcms/gitops

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  on-pr-comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@kiwitcms')
    # checkov:skip:CKV2_GHA_1:Action needs to write back comments & PRs
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: kiwitcms/gitops@v0.0.1
