name: kiwitcms/gitops

on:
  pull_request:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  on-pr-comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: |
            echo "---- event ----"
            echo ${{ github.event }}
            echo "---- comment ---"
            echo ${{ github.event.issue_comment }}

      - uses: actions/checkout@v4

      - name: Execute kiwitcms/gitops
        uses: ./ # Uses an action in the root directory
