name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        make-command: [flake8, pylint]

    name: ${{ matrix.make-command }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r devel.txt

      - name: Execute ${{ matrix.make-command }}
        run: |
          make ${{ matrix.make-command }}

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the container
        run: |
          docker build -t kiwitcms/gitops:devel .
          docker images
